name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: fin-rag-api    # Change this to your app name
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements-azure.txt

    - name: Create necessary directories
      run: |
        mkdir -p data embeddings metadata chunks temp_downloads

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Configure environment variables
      run: |
        az webapp config appsettings set \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group fin-rag-rg \
          --settings NVIDIA_API_KEY=${{ secrets.NVIDIA_API_KEY }} \
          --output table

    - name: Restart Azure Web App
      run: |
        az webapp restart \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group fin-rag-rg

    - name: Wait for deployment
      run: |
        sleep 30
        echo "Deployment completed. Checking status..."

    - name: Test deployment
      run: |
        echo "Testing deployment..."
        curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/docs || echo "App might still be starting up" 